- name: Install docker-compose and docker
  pip:
    name: 
    - docker-compose
    - docker

- name: Git checkout
  git:
    version: "{{ git_branch }}"
    repo: "{{ git_repository }}"
    dest: "{{ deployment_path }}"

- name: docker-compose up
  docker_compose:
    project_src: "{{ deployment_path }}"
    build: true
    debug: true